name: CI

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  phpmd:
    name: PHPMD
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Docker Compose stack
        run: docker compose up -d app --build

      - name: Install Composer dependencies
        run: docker compose run --rm app composer install --no-interaction --prefer-dist

      - name: Run PHPMD
        run: docker compose run --rm app composer phpmd
