name: CI

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  phpmd:
    name: PHPMD
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run PHPMD
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/project \
            -w /project \
            jakzal/phpqa:php8.4 \
            php -d error_reporting=22527 /tools/phpmd app text phpmd.xml
